name: Continuous Integration

# Trigger CI pipeline on pull requests and pushes to the main branch
on:
  pull_request: # Runs when a pull request is created or updated
    branches:
      - main
  push: # Runs on every push to the main branch
    branches:
      - main

jobs:
  test: # Define a testing job
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        # Check out the repository code into the workflow
        uses: actions/checkout@v3

      - name: Set up Python
        # Set up a Python environment using version 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        # Install required Python packages inside a virtual environment
        run: |
          python -m venv venv # Create a virtual environment
          source venv/bin/activate # Activate the virtual environment
          pip install -r api/requirements.txt # Install dependencies

      - name: Run tests
        # Execute pytest to validate the API functionality
        run: |
          source venv/bin/activate # Activate the virtual environment
          pytest api/tests/test_api.py # Run the test script
